package code

func init() {
	register(ErrSuccess, 200, "OK")
	register(ErrUserNotFound, 404, "User not found")
	register(ErrUserAlreadyExist, 400, "User already exist")
	register(ErrUnknown, 500, "Internal server error")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct")
	register(ErrValidation, 400, "Validation failed")
	register(ErrValidationCustom, 400, "")
	register(ErrTokenInvalid, 401, "Token invalid")
	register(ErrPageNotFound, 404, "Page not found")
	register(ErrDatabase, 500, "Database error")
	register(ErrRedis, 500, "Redis error")
	register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	register(ErrSignatureInvalid, 401, "Signature is invalid")
	register(ErrExpired, 401, "Token expired")
	register(ErrPasswordIncorrect, 401, "Password was incorrect")
	register(ErrPermissionDenied, 403, "Permission denied")
	register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")
	register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")
	register(ErrInvalidJSON, 500, "Data is not valid JSON")
	register(ErrEncodingJSON, 500, "JSON data could not be encoded")
	register(ErrDecodingJSON, 500, "JSON data could not be decoded")
	register(ErrInvalidYaml, 500, "Data is not valid Yaml")
	register(ErrEncodingYaml, 500, "Yaml data could not be encoded")
	register(ErrDecodingYaml, 500, "Yaml data could not be decoded")
	register(ErrGenerateToken, 500, "Token generate failed")
	register(ErrDBQueryDataFailed, 500, "Db query data failed")
	register(ErrDBAddDataFailed, 500, "Db add data failed")
	register(ErrDBUpdateDataFailed, 500, "Db update data failed")
	register(ErrDBDeleteDataFailed, 500, "Db delete data failed")
	register(ErrDataNotFound, 404, "Data not found")
	register(ErrUserNotRelateBrand, 500, "User is not related with this brand")

	register(ErrWxUserIsNotRegistered, 500, "WeChat user is not registered")
	register(ErrThePhoneHasBeenBoundToOtherWeChatUser, 500, "The phone has been bound to other Wechat user")

	// 从下面开始逐步替换成中文，英文没啥必要 后期全部替换
	register(ErrBrandNotFound, 404, "品牌未找到")
	register(ErrBrandExpired, 500, "品牌已过期")
	register(ErrUniminiNotOpen, 500, "未开通通用小程序")
	register(ErrUniminiExpired, 500, "通用小程序已过期")
	register(ErrMiniProgramUnauthorized, 500, "定制小程序未授权给三方平台")
	register(ErrMiniProgramNotOpenPay, 500, "定制小程序未开通支付")
}
